import { Divider, Flex, Text } from "@chakra-ui/react";
import Head from "next/head";

import { Banner } from "@/components/Banner";
import { ContinentsSlides } from "@/components/ContinentsSlides";
import { Header } from "@/components/Header";
import { TravelTypesSection } from "@/components/TravelTypesSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Worldtrip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="100%" flexDir="column" alignItems="center">
        <Header />

        <Banner />

        <TravelTypesSection />

        <Divider
          bg="gray.900"
          mt={{ base: "2.25rem", md: "5rem" }}
          w="5.625rem"
          h="0.125rem"
        />

        <Text
          flexWrap="wrap"
          my={{ base: "1.25rem", md: "3.25rem" }}
          color="gray.700"
          fontSize={{ base: "1.25rem", md: "3xl" }}
          fontWeight="normal"
          textAlign="center"
        >
          Vamos nessa? <br />
          Então escolha seu continente
        </Text>

        <ContinentsSlides />
      </Flex>
    </>
  );
}
